"""empty message

Revision ID: 752782ce0c90
Revises: 
Create Date: 2024-09-06 04:46:52.489327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752782ce0c90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('question1', sa.String(length=150), nullable=False),
    sa.Column('question2', sa.String(length=150), nullable=False),
    sa.Column('question3', sa.String(length=150), nullable=False),
    sa.Column('question4', sa.String(length=150), nullable=False),
    sa.Column('question5', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_submission')
    # ### end Alembic commands ###
